### PR TITLE
use source instead of var for table names

### PR DESCRIPTION
**Pull request by melissa-mg**

### CODE REVIEW

**Review by Skorch — CHANGES_REQUESTED** [review]
Changes look good.

Could you update the README.md to change the instructions on how to include this package into your project.  ie:  replace the comments about adding variables, and instead include an example of a sources.yml section

**Comment by melissa-mg** [comment]
updated the readme with my code from the dbt_project.yml file

**Comment by melissa-mg** [comment]
ok take a look now

**Review by Skorch — APPROVED** [review]
Looks good

**Pull request merged**
